extension HLOpCode {
    var id: HLOpCodeId {
        switch self {
        case .OMov: return .OMov
        case .OInt: return .OInt
        case .OFloat: return .OFloat
        case .OBool: return .OBool
        case .OBytes: return .OBytes
        case .OString: return .OString
        case .ONull: return .ONull
        case .OAdd: return .OAdd
        case .OSub: return .OSub
        case .OMul: return .OMul
        case .OSDiv: return .OSDiv
        case .OUDiv: return .OUDiv
        case .OSMod: return .OSMod
        case .OUMod: return .OUMod
        case .OShl: return .OShl
        case .OSShr: return .OSShr
        case .OUShr: return .OUShr
        case .OAnd: return .OAnd
        case .OOr: return .OOr
        case .OXor: return .OXor
        case .ONeg: return .ONeg
        case .ONot: return .ONot
        case .OIncr: return .OIncr
        case .ODecr: return .ODecr
        case .OCall0: return .OCall0
        case .OCall1: return .OCall1
        case .OCall2: return .OCall2
        case .OCall3: return .OCall3
        case .OCall4: return .OCall4
        case .OCallN: return .OCallN
        case .OCallMethod: return .OCallMethod
        case .OCallThis: return .OCallThis
        case .OCallClosure: return .OCallClosure
        case .OStaticClosure: return .OStaticClosure
        case .OInstanceClosure: return .OInstanceClosure
        case .OVirtualClosure: return .OVirtualClosure
        case .OGetGlobal: return .OGetGlobal
        case .OSetGlobal: return .OSetGlobal
        case .OField: return .OField
        case .OSetField: return .OSetField
        case .OGetThis: return .OGetThis
        case .OSetThis: return .OSetThis
        case .ODynGet: return .ODynGet
        case .ODynSet: return .ODynSet
        case .OJTrue: return .OJTrue
        case .OJFalse: return .OJFalse
        case .OJNull: return .OJNull
        case .OJNotNull: return .OJNotNull
        case .OJSLt: return .OJSLt
        case .OJSGte: return .OJSGte
        case .OJSGt: return .OJSGt
        case .OJSLte: return .OJSLte
        case .OJULt: return .OJULt
        case .OJUGte: return .OJUGte
        case .OJNotLt: return .OJNotLt
        case .OJNotGte: return .OJNotGte
        case .OJEq: return .OJEq
        case .OJNotEq: return .OJNotEq
        case .OJAlways: return .OJAlways
        case .OToDyn: return .OToDyn
        case .OToSFloat: return .OToSFloat
        case .OToUFloat: return .OToUFloat
        case .OToInt: return .OToInt
        case .OSafeCast: return .OSafeCast
        case .OUnsafeCast: return .OUnsafeCast
        case .OToVirtual: return .OToVirtual
        case .OLabel: return .OLabel
        case .ORet: return .ORet
        case .OThrow: return .OThrow
        case .ORethrow: return .ORethrow
        case .OSwitch: return .OSwitch
        case .ONullCheck: return .ONullCheck
        case .OTrap: return .OTrap
        case .OEndTrap: return .OEndTrap
        case .OGetI8: return .OGetI8
        case .OGetI16: return .OGetI16
        case .OGetMem: return .OGetMem
        case .OGetArray: return .OGetArray
        case .OSetI8: return .OSetI8
        case .OSetI16: return .OSetI16
        case .OSetMem: return .OSetMem
        case .OSetArray: return .OSetArray
        case .ONew: return .ONew
        case .OArraySize: return .OArraySize
        case .OType: return .OType
        case .OGetType: return .OGetType
        case .OGetTID: return .OGetTID
        case .ORef: return .ORef
        case .OUnref: return .OUnref
        case .OSetref: return .OSetref
        case .OMakeEnum: return .OMakeEnum
        case .OEnumAlloc: return .OEnumAlloc
        case .OEnumIndex: return .OEnumIndex
        case .OEnumField: return .OEnumField
        case .OSetEnumField: return .OSetEnumField
        case .OAssert: return .OAssert
        case .ORefData: return .ORefData
        case .ORefOffset: return .ORefOffset
        case .ONop: return .ONop
        }
    }
}